services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: recipe
      POSTGRES_PASSWORD: recipe
      POSTGRES_DB: recipe
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
