syntax = "proto3";

package recipe;

option go_package = "github.com/kodaikumatani/grpc-cqrs-go/pkg/pb/recipe";

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

service RecipeService {
  rpc CreateRecipe(CreateRecipeRequest) returns (CreateRecipeResponse);
  rpc GetRecipe(GetRecipeRequest) returns (GetRecipeResponse);
  rpc UpdateRecipe(UpdateRecipeRequest) returns (UpdateRecipeResponse);
  rpc ChangeVisibility(ChangeVisibilityRequest) returns (ChangeVisibilityResponse);
}

enum Visibility {
  VISIBILITY_UNSPECIFIED = 0;
  VISIBILITY_PUBLIC = 1;
  VISIBILITY_PRIVATE = 2;
  VISIBILITY_RESTRICTED = 3;
}

message Recipe {
  string id = 1;
  string user_id = 2;
  string title = 3;
  string description = 4;
  google.protobuf.Timestamp created_at = 5;
  google.protobuf.Timestamp updated_at = 6;
  Visibility visibility = 7;
}

message CreateRecipeRequest {
  string title = 2 [(buf.validate.field).string = {min_len: 1, max_len: 100}];
  string description = 3 [(buf.validate.field).string.max_len = 1000];
}

message CreateRecipeResponse { string recipe_id = 1; }

message GetRecipeRequest {
  string id = 1 [(buf.validate.field).string.uuid = true];
}

message GetRecipeResponse { Recipe recipe = 1; }

message UpdateRecipeRequest {
  string id = 1 [(buf.validate.field).string.uuid = true];
  string title = 2 [(buf.validate.field).string = {min_len: 1, max_len: 100}];
  string description = 3 [(buf.validate.field).string.max_len = 1000];
}

message UpdateRecipeResponse { bool success = 1; }

message ChangeVisibilityRequest {
  string id = 1 [(buf.validate.field).string.uuid = true];
  Visibility visibility = 2 [(buf.validate.field).enum = {
    defined_only: true
    not_in: [0]
  }];
}

message ChangeVisibilityResponse { bool success = 1; }
